services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: whale_user
      POSTGRES_PASSWORD: whale_password
      POSTGRES_DB: whale_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
